version: '3'
services:
  marketplace.api:
    image: marketplace-api:latest
    container_name: marketplace-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
