version: '3'
services:
  marketplace-api:
    image: marketplace:latest
    container_name: marketplace-api
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./.env:/opt/app/.env
